version: '3.8'

services:
  backup:
    image: itzg/mc-backup
    env_file:
      - rcon.env
  sftp:
    image: atmoz/sftp
    environment:
      - SFTP_USERS=sftp:enter_your_password_in_here:1001
    ports:
      - "25522:22"
