version: '3.8'

services:
  minecraft-common:
    image: itzg/minecraft-server
    env_file:
      - rcon.env
      - .env
    environment:
      - EULA=TRUE
    ports:
      - 25565:25565/TCP
    # https://man7.org/linux/man-pages/man7/capabilities.7.html
    cap_add:
      # As we are already isolated, we do not require any permission checks
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
      - CAP_KILL
      - CAP_NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_ADMIN
    dns:
      - 8.8.8.8
      - 8.8.4.4
    
    
